# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0005_auto_20171101_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='continguts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
