# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0006_prova_continguts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='alumne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nota_alumne', to='alumnes.Alumne'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_prova', to='proves.Prova'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='assignatura',
            field=models.ForeignKey(default='Adria Moya Ortiz', on_delete=django.db.models.deletion.CASCADE, related_name='proves_assignatura', to='assignatures.Assignatura'),
            preserve_default=False,
        ),
    ]
