# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0006_trimestre'),
        ('proves', '0007_remove_prova_curs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='assignatura',
        ),
        migrations.AddField(
            model_name='prova',
            name='trimestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proves_trimestre', to='assignatures.Trimestre'),
        ),
    ]
