# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0007_auto_20171203_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='alumne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_alumne', to='alumnes.Alumne'),
        ),
    ]
