# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0011_auto_20171213_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
