# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0012_auto_20171213_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.FloatField(),
        ),
    ]
