# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignatures', '0001_initial'),
        ('classes', '0001_initial'),
        ('proves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignatura',
            name='classes',
            field=models.ManyToManyField(blank=True, to='classes.Classe'),
        ),
        migrations.AddField(
            model_name='assignatura',
            name='proves',
            field=models.ManyToManyField(blank=True, related_name='assignatura_proves', to='proves.Prova'),
        ),
    ]
