# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('assignatures', '0002_auto_20171029_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignatura',
            name='professors',
            field=models.ManyToManyField(blank=True, related_name='assignatura_professors', to='classes.Professor'),
        ),
    ]
