# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0003_assignatura_professors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignatura',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='assignatura',
            name='professors',
        ),
        migrations.RemoveField(
            model_name='assignatura',
            name='proves',
        ),
    ]
