# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0004_auto_20171029_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignatura',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignatura',
            name='curs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
