# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0006_trimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaluacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('curs', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trimestre',
            name='assignatura',
        ),
    ]
