# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0009_auto_20171210_1822'),
        ('assignatures', '0007_auto_20171210_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trimestre',
        ),
        migrations.AddField(
            model_name='avaluacio',
            name='assignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaluacio_assignatura', to='assignatures.Assignatura'),
        ),
    ]
