# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0009_auto_20171210_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignatura',
            name='curs',
        ),
    ]
