# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0013_auto_20171210_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignatura',
            name='curs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curs_assignatures', to='cursos.Curs'),
        ),
        migrations.AlterField(
            model_name='avaluacio',
            name='assignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignatura_avaluacions', to='assignatures.Assignatura'),
        ),
    ]
