# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_auto_20171031_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='birth_date',
            new_name='data_naixement',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='user',
            new_name='usuari',
        ),
        migrations.AddField(
            model_name='professor',
            name='cognoms',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='professor',
            name='nom',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
