# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_auto_20171031_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='cognoms',
            new_name='primer_cognom',
        ),
        migrations.AddField(
            model_name='professor',
            name='segon_cognom',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
