# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professors', '0009_auto_20171031_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
