# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('assignatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120)),
                ('primer_cognom', models.CharField(blank=True, max_length=120)),
                ('segon_cognom', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('lloc', models.CharField(blank=True, max_length=30)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('assignatures', models.ManyToManyField(blank=True, related_name='alumne_assignatures', to='assignatures.Assignatura')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumne_classe', to='classes.Classe')),
            ],
        ),
    ]
