# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignatures', '0001_initial'),
        ('classes', '0001_initial'),
        ('alumnes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='assignatures',
            field=models.ManyToManyField(blank=True, to='assignatures.Assignatura'),
        ),
        migrations.AddField(
            model_name='alumne',
            name='classe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Classe'),
        ),
    ]
