# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0002_auto_20171029_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='assignatures',
            field=models.ManyToManyField(blank=True, related_name='alumne_assignatures', to='assignatures.Assignatura'),
        ),
    ]
