# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0003_auto_20171030_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alumne',
            name='data_naixement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumne',
            name='lloc',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='nom',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='primer_cognom',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
