# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0004_auto_20171101_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumne_classe', to='classes.Classe'),
        ),
    ]
