# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0005_auto_20171207_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
