# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignatures', '0014_auto_20171210_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('pes_total', models.FloatField()),
                ('nota_total', models.FloatField()),
                ('nota_mitja', models.FloatField(blank=True, null=True)),
                ('avaluacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaluacio_dimensions', to='assignatures.Avaluacio')),
            ],
        ),
    ]
