# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('assignatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('pes_total', models.FloatField()),
                ('nota_total', models.FloatField()),
                ('nota_mitja', models.FloatField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('avaluacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensions_avaluacio', to='assignatures.Avaluacio')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('dimensio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdimensions', to='dimensions.Dimensio')),
            ],
        ),
    ]
