# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0006_auto_20171207_1835'),
        ('dimensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_Dimensio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('alumne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumne_notes_dimensio', to='alumnes.Alumne')),
                ('dimensio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensio_notes', to='dimensions.Dimensio')),
            ],
        ),
    ]
