# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0002_nota_dimensio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensio',
            name='avaluacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensions_avaluacio', to='assignatures.Avaluacio'),
        ),
    ]
