# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0005_auto_20171226_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensio',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='dimensio',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
