# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0006_auto_20171226_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensio',
            name='dimensio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensio_parent', to='dimensions.Dimensio'),
        ),
    ]
