# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120)),
                ('primer_cognom', models.CharField(blank=True, max_length=120)),
                ('segon_cognom', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('lloc', models.CharField(blank=True, max_length=30)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('assignatures', models.ManyToManyField(blank=True, related_name='professor_assignatures', to='assignatures.Assignatura')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
