# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0004_auto_20171029_2234'),
        ('professors', '0003_auto_20171031_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='location',
            new_name='lloc',
        ),
        migrations.AddField(
            model_name='professor',
            name='assignatures',
            field=models.ManyToManyField(blank=True, related_name='professor_assignatures', to='assignatures.Assignatura'),
        ),
    ]
