# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_auto_20171031_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='usuari',
            new_name='User',
        ),
    ]
