# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignatures', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('assignatures', models.ManyToManyField(blank=True, related_name='classe_assignatures', to='assignatures.Assignatura')),
                ('curs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curs_classes', to='cursos.Curs')),
            ],
        ),
    ]
