# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('curs', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('primer_cognom', models.CharField(max_length=120)),
                ('segon_cognom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('assignatures', models.ManyToManyField(blank=True, to='assignatures.Assignatura')),
                ('classes', models.ManyToManyField(blank=True, related_name='professor_classes', to='classes.Classe')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='professors',
            field=models.ManyToManyField(blank=True, related_name='classe_professors', to='classes.Professor'),
        ),
    ]
