# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0002_auto_20171029_1550'),
        ('classes', '0002_classe_alumnes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='alumnes',
        ),
        migrations.AddField(
            model_name='classe',
            name='alumnes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe_alumnes', to='alumnes.Alumne'),
        ),
    ]
