# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0002_auto_20171029_1550'),
        ('classes', '0003_auto_20171029_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='alumnes',
        ),
        migrations.AddField(
            model_name='classe',
            name='alumnes',
            field=models.ManyToManyField(blank=True, related_name='classe_alumnes', to='alumnes.Alumne'),
        ),
    ]
