# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20171029_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='professors',
        ),
    ]
