# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_classe_alumnes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='assignatures',
            field=models.ManyToManyField(blank=True, related_name='professor_assignatures', to='assignatures.Assignatura'),
        ),
    ]
