# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20171030_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='assignatures',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='classes',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
