# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignatures', '0005_auto_20171201_1510'),
        ('classes', '0008_auto_20171031_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='assignatures',
            field=models.ManyToManyField(blank=True, related_name='classe_assignatures', to='assignatures.Assignatura'),
        ),
    ]
