# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0004_auto_20171101_0714'),
        ('classes', '0009_classe_assignatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='alumnes',
            field=models.ManyToManyField(blank=True, related_name='classe_alumnes', to='alumnes.Alumne'),
        ),
    ]
