# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_classe_alumnes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='alumnes',
        ),
    ]
