# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('classes', '0011_remove_classe_alumnes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='curs',
        ),
        migrations.AddField(
            model_name='classe',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='cursos_classes', to='cursos.Curs'),
        ),
    ]
