# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_auto_20171210_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='cursos',
            new_name='curs',
        ),
    ]
