# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_auto_20171210_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='curs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curs_classes', to='cursos.Curs'),
        ),
    ]
