# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0002_auto_20171029_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='prova',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_prova', to='proves.Prova'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='assignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proves_assignatura', to='assignatures.Assignatura'),
        ),
    ]
