# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0006_prova_continguts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='curs',
        ),
    ]
