# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0009_auto_20171210_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='nota_mitja',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
