# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0010_prova_nota_mitja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
