# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('proves', '0013_auto_20171213_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='avaluacio',
        ),
        migrations.AddField(
            model_name='prova',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prova',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
