# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('proves', '0014_auto_20171226_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='alumne',
        ),
        migrations.AddField(
            model_name='nota',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='nota',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
