# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0015_auto_20171226_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
