# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0006_auto_20171207_1835'),
        ('proves', '0016_auto_20171226_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='alumne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumne', to='alumnes.Alumne'),
        ),
    ]
