# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proves', '0017_nota_alumne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='prova',
        ),
    ]
